# Project's GitLab CI configuration

# Use the global node.js docker image
image: node

# Global Vars
variables:
  PKG_NAME: "ra-web-decimal-to-twoscomplement"

# Global Caching rules, enabled per-ref caching
cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - assets/vendor/

# First install bower and gulp-cli globally and then
# install/require all dependencies
before_script:
  - npm install -g bower gulp-cli
  - npm install
  - bower install --allow-root

stages:
  - lint
  - build
  - deployment

lint:all:
  stage: lint
  script: gulp lint
  allow_failure: true

build:all:
  stage: build
  only:
   - master
  script:
    - gulp build
    - find assets/dist/ -name *.map -type f -exec rm -f {} \;
  artifacts:
    name: "${PKG_NAME}_${CI_BUILD_REF}"
    paths:
      - assets/dist/
      - assets/vendor/
      - ./*.html

deploy:production:
  stage: deployment
  environment: production
  only:
    - master
  dependencies:
    - build:all
  before_script:
    - apt-get update >> /dev/null && apt-get install -y rsync git >> /dev/null
    - 'which ssh-agent || ( apt-get install openssh-client -y >> /dev/null )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PROD_SSH_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script: rsync -rtvhze ssh . $PROD_SSH_USER@$PROD_HOST:$PROD_PATH --exclude=.git/ --exclude=.gitmodules --exclude=README.md --exclude=.gitlab-ci.yml --exclude=assets/src/ --stats --delete